name: navigation
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.0.1"

dependencies:
  auto_route: ^7.4.0
  flutter:
    sdk: flutter

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  domain:
    path: ../domain
  auth:
    path: ../features/auth

dev_dependencies:
  flutter_lints: ^2.0.1
  auto_route_generator: ^7.0.0
  build_runner: ^2.3.3
